name: Terraform uat deployment
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  Terraform:
    name: terraform deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform'
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: 'eu-west-2'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=gsk-terraform-statefile"

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve